
# generic AWS Codebuild build script for cognify modules.  Produces a zip file of the 'lambda' sub-directory
# For the AWS specification see http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  build:
    commands:
      - echo Build started
      # hop into the lambda directory
      - cd lambda
       # determine package name
      - packageName=$( node -pe "require('./package.json').name" )
      # determine version
      - version=$( node -pe "require('./package.json').version" )
      - echo Building $packageName version $version
      - npm install
      # created 'build-output' directory to hold build
      - mkdir build-output
      # copy all files into this directory
      - cp *.* build-output
      # copy the lib folder
      - cp -r lib build-output
      # navigate into this folder
      - cd build-output
      # run install within build-output folder.  Only production dependencies are installed
      - npm install --production
      # zip up the contents of the build-output folder, name this file name~version.zip
      - zip -r $packageName~$version.zip ./*
artifacts:
  files:
    # build artifact is a single zip file, i.e. the zip file produced in the build phase above
    - $packageName~$version.zip
  base-directory: lambda/build-output